### ISSUE TITLE
Unable to compile on Ubuntu 11.10

### ISSUE THREAD

**Issue by CaledoniaProject** [sqlcipher/sqlcipher#17]
Hi,

I'm trying to compile with:

./configure --disable-tcl --enable-tempstore=yes --enable-releasemode --disable-amalgamation

But the final link failed with:

./.libs/libsqlite3.so: undefined reference to `sqlcipher_exportFunc'

Any clue ?
