### ISSUE TITLE
Xcode 7.3 compilation errors

### ISSUE THREAD

**Issue by groue** [sqlcipher/sqlcipher#162]
Hello,

The sqlcipher.xcodeproj Xcode project won't compile with Xcode 7.3:

When building for OX:

```
Undefined symbols for architecture x86_64:
  "_sqlite3LimitWhere", referenced from:
      _yy_reduce in libsqlcipher.a(sqlite3.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

When building for iOS:

```
/.../sqlite3.c:128906:27: error: implicit declaration of function 'sqlite3LimitWhere' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  yymsp[-2].minor.yy132 = sqlite3LimitWhere(pParse, yymsp[-4].minor.yy65, yymsp[-2].minor.yy132, yymsp[-1].minor.yy14, yymsp[0].minor.yy476.pLimit, yymsp[0].minor.yy476.pOffset, "DELETE");
```

It happens that the sqlite3LimitWhere function is declared in sqlite3.c, guarded by a preprocessor check:

```c
#if defined(SQLITE_ENABLE_UPDATE_DELETE_LIMIT) && !defined(SQLITE_OMIT_SUBQUERY)
SQLITE_PRIVATE Expr *sqlite3LimitWhere(Parse*,SrcList*,Expr*,ExprList*,Expr*,Expr*,char*);
#endif
```

It is later defined, also guarded by the same preprocessor check:

```c
#if defined(SQLITE_ENABLE_UPDATE_DELETE_LIMIT) && !defined(SQLITE_OMIT_SUBQUERY)
/*
** Generate an expression tree to implement the WHERE, ORDER BY,
** and LIMIT/OFFSET portion of DELETE and UPDATE statements.
**
**     DELETE FROM table_wxyz WHERE a<5 ORDER BY a LIMIT 1;
**                            \__________________________/
**                               pLimitWhere (pInClause)
*/
SQLITE_PRIVATE Expr *sqlite3LimitWhere(
  Parse *pParse,               /* The parser context */
  SrcList *pSrc,               /* the FROM clause -- which tables to scan */
  Expr *pWhere,                /* The WHERE clause.  May be null */
  ExprList *pOrderBy,          /* The ORDER BY clause.  May be null */
  Expr *pLimit,                /* The LIMIT clause.  May be null */
  Expr *pOffset,               /* The OFFSET clause.  May be null */
  char *zStmtType              /* Either DELETE or UPDATE.  For err msgs. */
){
```

But when it is used later in the `yy_reduce()` function, it is not guarded. Hence the errors.

The [SQLite documentation](https://www.sqlite.org/compile.html#enable_update_delete_limit) says:

> SQLITE_ENABLE_UPDATE_DELETE_LIMIT
> 
> This option enables an optional ORDER BY and LIMIT clause on UPDATE and DELETE statements.
> 
> If this option is defined, then it must also be defined when using the 'lemon' tool to generate a parse.c file. Because of this, **this option may only be used when the library is built from source, not from the amalgamation** or from the collection of pre-packaged C files provided for non-Unix like platforms on the website.

(Emphasis mine). The sqlcipher.xcodeproj builds libsqlcipher.a from the amalgation, so we can't just add the `-DSQLITE_ENABLE_UPDATE_DELETE_LIMIT` to the compiler option.

Do you know how we can fix this error?

**Comment by sjlombardo** [comment]
@groue I just tried a simple build of  sqlcipher.xcodeproj using XC, and didn't run into any compilation issues.  I'm not sure that you have your project setup correctly. If you need to adjust CFLAGS, you'd  that in the project settings etc. Your project should also be linking against the generated libsqlcipher.a, not including sqlite3.c directly. Can you confirm that you have things setup correctly?

**Comment by sjlombardo** [comment]
@groue as a follow up request: it is unclear from your post whether you are trying to produce a build with SQLITE_ENABLE_UPDATE_DELETE_LIMIT, and are seeing the error, or if you are trying to build without SQLITE_ENABLE_UPDATE_DELETE_LIMIT but are seeing the error. Can you clarify?

**Comment by groue** [comment]
Hello @sjlombardo.

I don't quite know what *was* happening. Because I can't reproduce it now. I'm really sorry for the inconvenience.

I didn't dream the errors above, and started tweaking sqlcipher.xcodeproj only after they occurred, but now when I reset the SQLCipher repo to v3.3.1, no error is happening (???). I was trying to build the stock v3.3.1 SQLCipher, without SQLITE_ENABLE_UPDATE_DELETE_LIMIT.

Sorry again. And thank you.

**Comment by groue** [comment]
And I'm now using my [own set of options](https://github.com/groue/sqlcipher/blob/fix1/sqlcipher.xcconfig) that better match the stock SQLite shipped with and OSX/iOS, without SQLITE_ENABLE_UPDATE_DELETE_LIMIT.

**Comment by groue** [comment]
The goal is to grant SQLCipher support to http://github.com/groue/GRDB.swift

**Comment by brodybits** [comment]
@groue these look really cool. I may use your settings in my Cordova adapter.

**Comment by groue** [comment]
@brodybits Go ahead :-)
