### ISSUE TITLE
Invalid syntax with macro check for __has_feature

### ISSUE THREAD

**Issue by barracuda156** [sqlcipher/sqlcipher#572]
Existing code does not compile, when `__has_feature` is not supported:
```
/usr/bin/gcc-4.2 -dynamic -pipe -I/opt/local/libexec/openssl3/include -Os -arch ppc -DSQLITE_DISABLE_INTRINSIC -DSQLITE_SECURE_DELETE -DSQLITE_SOUNDEX -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0 -DSQLCIPHER_OMIT_LOG_DEVICE -DSQLITE_EXTRA_INIT=sqlcipher_extra_init -DSQLITE_EXTRA_SHUTDOWN=sqlcipher_extra_shutdown -DSQLITE_TEMP_STORE=2 -DSQLITE_HAS_CODEC -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_THREADSAFE=1    -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -I. -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0/src -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0/ext/rtree -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0/ext/icu -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0/ext/fts3 -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0/ext/session -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0/ext/misc -c sqlite3.c
/usr/bin/gcc-4.2 -dynamic -pipe -I/opt/local/libexec/openssl3/include -Os -arch ppc -DSQLITE_DISABLE_INTRINSIC -DSQLITE_SECURE_DELETE -DSQLITE_SOUNDEX -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0 -DSQLCIPHER_OMIT_LOG_DEVICE -DSQLITE_EXTRA_INIT=sqlcipher_extra_init -DSQLITE_EXTRA_SHUTDOWN=sqlcipher_extra_shutdown -DSQLITE_TEMP_STORE=2 -DSQLITE_HAS_CODEC -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_THREADSAFE=1    -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -I. -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0/src -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0/ext/rtree -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0/ext/icu -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0/ext/fts3 -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0/ext/session -I/opt/local/var/macports/build/sqlcipher-0dae138c/work/sqlcipher-4.10.0/ext/misc  -o sqlite3 \
        shell.c sqlite3.c \
         \
        -I/usr/include -DHAVE_EDITLINE=1 -DSQLITE_HAVE_ZLIB=1 -DSQLITE_DQS=0 -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_EXPLAIN_COMMENTS -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_BYTECODE_VTAB -DSQLITE_ENABLE_OFFSET_SQL_FUNC -DSQLITE_STRICT_SUBTYPE=1  \
            -lz   -L/opt/local/libexec/openssl3/lib -L/opt/local/lib -Wl,-headerpad_max_install_names -lcrypto -arch ppc -ledit -lncurses
sqlite3.c:108730:48: error: missing binary operator before token "("
gnumake: *** [sqlite3.o] Error 1
gnumake: *** Waiting for unfinished jobs....
sqlite3.c:108730:48: error: missing binary operator before token "("
gnumake: *** [sqlite3] Error 1
```

The bug introduced in https://github.com/sqlcipher/sqlcipher/commit/1eef2b438442c46cf40d690530d7b19c9c40ceed

FYI @sjlombardo
