### ISSUE TITLE
Build of 4.6.0 fails: `error: os/log.h: No such file or directory`; `error: ‘OS_LOG_DEFAULT’ undeclared (first use in this function)`

### ISSUE THREAD

**Issue by barracuda156** [sqlcipher/sqlcipher#518]
### Expected Behavior
The build should succeed.

### Actual Behavior
But it fails:
```
libtool: link: /usr/bin/gcc-4.2 -std=gnu99 -DSQLITE_DISABLE_INTRINSIC -DSQLITE_SECURE_DELETE -DSQLITE_SOUNDEX -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_databases_sqlcipher/sqlcipher/work/sqlcipher-4.6.0 -DSQLITE_HAS_CODEC -I/opt/local/libexec/openssl3/include -isystem/opt/local/include -pipe -I/opt/local/libexec/openssl3/include -Os -arch ppc -DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_OS_UNIX=1 -I. -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_databases_sqlcipher/sqlcipher/work/sqlcipher-4.6.0/src -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_databases_sqlcipher/sqlcipher/work/sqlcipher-4.6.0/ext/rtree -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_databases_sqlcipher/sqlcipher/work/sqlcipher-4.6.0/ext/icu -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_databases_sqlcipher/sqlcipher/work/sqlcipher-4.6.0/ext/fts3 -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_databases_sqlcipher/sqlcipher/work/sqlcipher-4.6.0/ext/async -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_databases_sqlcipher/sqlcipher/work/sqlcipher-4.6.0/ext/session -I/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_databases_sqlcipher/sqlcipher/work/sqlcipher-4.6.0/ext/userauth -D_HAVE_SQLITE_CONFIG_H -DBUILD_sqlite -DNDEBUG -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_MATH_FUNCTIONS -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_STAT4 -DSQLITE_ENABLE_UNLOCK_NOTIFY -DSQLITE_HAVE_ZLIB=1 -Wl,-headerpad_max_install_names -arch ppc -DHAVE_READLINE=0 -DHAVE_EDITLINE=1 -DHAVE_LINENOISE=0 -DSQLITE_DQS=0 -DSQLITE_ENABLE_FTS4 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_EXPLAIN_COMMENTS -DSQLITE_ENABLE_UNKNOWN_SQL_FUNCTION -DSQLITE_ENABLE_STMTVTAB -DSQLITE_ENABLE_DBPAGE_VTAB -DSQLITE_ENABLE_DBSTAT_VTAB -DSQLITE_ENABLE_BYTECODE_VTAB -DSQLITE_ENABLE_OFFSET_SQL_FUNC -DSQLITE_STRICT_SUBTYPE=1 -o sqlcipher shell.c sqlite3.c  -L/opt/local/libexec/openssl3/lib -L/opt/local/lib /opt/local/lib/libedit.dylib -lz -lcrypto
sqlite3.c:106568:20: error: os/log.h: No such file or directory
sqlite3.c: In function ‘sqlcipher_profile_callback’:
sqlite3.c:109807: warning: implicit declaration of function ‘os_log’
sqlite3.c:109807: error: ‘OS_LOG_DEFAULT’ undeclared (first use in this function)
sqlite3.c:109807: error: (Each undeclared identifier is reported only once
sqlite3.c:109807: error: for each function it appears in.)
sqlite3.c: In function ‘sqlcipher_log’:
sqlite3.c:109895: error: ‘OS_LOG_DEFAULT’ undeclared (first use in this function)
gnumake: *** [sqlite3.lo] Error 1
gnumake: *** Waiting for unfinished jobs....
sqlite3.c:106568:20: error: os/log.h: No such file or directory
sqlite3.c: In function 'sqlcipher_profile_callback':
sqlite3.c:109807: warning: implicit declaration of function 'os_log'
sqlite3.c:109807: error: 'OS_LOG_DEFAULT' undeclared (first use in this function)
sqlite3.c:109807: error: (Each undeclared identifier is reported only once
sqlite3.c:109807: error: for each function it appears in.)
sqlite3.c: In function 'sqlcipher_log':
sqlite3.c:109895: error: 'OS_LOG_DEFAULT' undeclared (first use in this function)
gnumake: *** [sqlcipher] Error 1
```
### Steps to Reproduce
Build on macOS 10.6

SQLCipher version:
4.6.0

**Comment by sjlombardo** [comment]
Hello @barracuda156 it looks like you're building for a very  old version of macOS that doesn't include the requisite support for `os_log`. I would suggest adding `-DSQLCIPHER_OMIT_LOG_DEVICE` to your compile flags.

**Comment by barracuda156** [comment]
@sjlombardo I will try, thank you.

If this is relying on SDK, then we can rather fix it for everyone, adding a conditional macro. `AvailabilityMacros.h` has everything needed.

**Comment by barracuda156** [comment]
@sjlombardo Looks like `log.h` can be used on 10.12+, while earlier ASL should be used: https://groups.google.com/a/chromium.org/g/crashpad-dev/c/5CY_M9R6mIw?pli=1

**Comment by barracuda156** [comment]
Compiling with `-DSQLCIPHER_OMIT_LOG_DEVICE`. Is it possible to use ASL as a fallback or the only way is to keep logging disabled?

**Comment by sjlombardo** [comment]
Hi @barracuda156 - After review, we have decided not to make any further changes related to ASL. Versions of  macOS 10.11 went off support over 6 years ago. We don't have any devices we we could even use to test a change like this. Even if you have used `SQLCIPHER_OMIT_LOG_DEVICE`, you can still get configure log output to a separate file which is very flexible.

**Comment by barracuda156** [comment]
@sjlombardo Got it. Well, as long as it works generally, we can live with that. Passing an extra flag from portfile code is not a problem.
